# Generated by Django 4.1.7 on 2023-02-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelloWorld',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('print', models.CharField(default='Hello world!', max_length=255)),
                ('extra', models.CharField(default='', max_length=255, null=True)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('from_api', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
